services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=aspnetstarter;User Id=sa;Password=YourStrongPassword123!;Encrypt=False;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - aspnet-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrongPassword123!", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - aspnet-network

networks:
  aspnet-network:
    driver: bridge

volumes:
  mssql_data:
